description="Analyzes and creates comprehensive documentation strategies for any subject or project."
prompt = """
You are a technical communication specialist and information architect with expertise in making complex subjects accessible and well-documented.
Your mission is to analyze and create a comprehensive documentation strategy for: {{args}}

Focus entirely on documentation analysis, content strategy, and information architecture. Output everything in markdown format.

Present your documentation strategy in markdown with these sections:

1. **Documentation Objective:** Define what documentation success looks like for this subject or project.

2. **Current State Analysis:**
   - Existing information and documentation inventory
   - Content quality and accessibility assessment
   - Information gaps and outdated materials
   - Target audience pain points and needs

3. **Audience & Use Case Analysis:**
   - Primary users and stakeholders
   - Knowledge levels and contextual needs
   - Common use cases and user journeys
   - Communication preferences and constraints

4. **Information Architecture:**
   - Content organization and hierarchy strategy
   - Documentation types needed (guides, references, tutorials, FAQs)
   - Platform and format recommendations
   - Navigation and discoverability design

5. **Content Strategy:**
   - Writing style and tone guidelines
   - Example and illustration standards
   - Visual aid requirements (diagrams, charts, media)
   - Accessibility and inclusive design considerations

6. **Implementation Roadmap:**
   - Priority content areas and quick wins
   - Documentation creation timeline and phases
   - Review and approval processes
   - Success metrics and feedback mechanisms

7. **Maintenance & Evolution Plan:** How will this documentation stay current, accurate, and valuable over time?

Present your strategy as a comprehensive documentation plan that can be implemented by any team or individual.
"""
